Newsweek clone built with Bootstrap 4
SajjadAhmad14/Newsweek-Clone pull request #3
Opened 2020-06-28 21:06 UTC by SajjadAhmad14

This web project is inspired by the design of Newsweek.com. It's built with HTML, CSS, and Bootstrap4.
Bootstrap Grid System has been used to layout web pages for three viewports.
Bootstrap spacing utilities have been used for margin and padding.
Bootstrap navbar classed have been utilized to layout navigation bars.

2020-06-28 22:31 UTC, HADDADSOHAIB requested changes
### Status: Chnages required :recycle: 

### Hi @SajjadAhmad14  :hand: 

### Your project is looking good, but there is some changes to be made:
- Yours are using STickler in your project, You have to use Github Actions instead, go to https://github.com/microverseinc/linters-config/tree/master/html-css and flow the necessary steps.
- In medium widths, the navbar is overlapping over section titles.
clone:
![Screenshot from 2020-06-28 23-13-55](https://user-images.githubusercontent.com/26064042/85959572-2ded1800-b995-11ea-8419-3d4852c96a28.png)
original:
![Screenshot from 2020-06-28 23-15-26](https://user-images.githubusercontent.com/26064042/85959598-49582300-b995-11ea-801d-836160a4e254.png)
- There are some images that are broken:
![Screenshot from 2020-06-28 23-16-07](https://user-images.githubusercontent.com/26064042/85959633-6c82d280-b995-11ea-881f-4bd13629c194.png)
![Screenshot from 2020-06-28 23-17-17](https://user-images.githubusercontent.com/26064042/85959658-90deaf00-b995-11ea-870d-82ff68c095c4.png)
![Screenshot from 2020-06-28 23-17-25](https://user-images.githubusercontent.com/26064042/85959660-976d2680-b995-11ea-9462-fc85c56402f7.png)
- In large widths ( over 2000 px) your nav bar expand and the page stay fixed, please fix that:
clone
![Screenshot from 2020-06-28 23-28-39](https://user-images.githubusercontent.com/26064042/85959911-4b22e600-b997-11ea-82f0-c38e69d7556d.png)
original
![Screenshot from 2020-06-28 23-30-30](https://user-images.githubusercontent.com/26064042/85959922-6130a680-b997-11ea-89bf-960d5702cac5.png)

### Once you are done with the changes, please ask for another code review.

2020-06-30 00:37 UTC, elmejdki requested changes
# Status: require changes :recycle: 
## Great job so far guys :clap:  :clap:  :clap:, your clone almost matches the original but in order to get it approved you need to make some changes :hammer: :hammer_and_wrench: :wrench: :toolbox: 

- [ ] center the text inside the navbar:
### clone: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86068818-2c445280-ba70-11ea-807d-c2ba126629ad.png)
 ### original: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86068847-3d8d5f00-ba70-11ea-841c-683d569afd92.png)

- [ ] Remove border-bottom on the last article, and make the images wider:
### clone: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069051-b8567a00-ba70-11ea-8596-c4075d6936e0.png)
### original: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069104-df14b080-ba70-11ea-816c-d1a7346104c6.png)

- [ ] Fix the subscribe and newsletter section, it should look similar to the original:
### clone: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069175-0d928b80-ba71-11ea-8c4f-2b7f1bee7298.png)

### original: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069163-03708d00-ba71-11ea-9b18-a78539870c72.png)

- [ ] change the size of the logo to match the original on table view:
### clone:  :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069274-59453500-ba71-11ea-8e07-99ce82a1f234.png)
### original: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069302-68c47e00-ba71-11ea-8b03-5dcef1b9ab59.png)

- [ ] Fix the form bellow opinion section on tablet view:
### clone: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069365-8e518780-ba71-11ea-814c-21c5e1a58845.png)
### original: :point_down: :point_down:  :point_down:  :point_down:  :point_down: 
![image](https://user-images.githubusercontent.com/34653764/86069379-97425900-ba71-11ea-9c9c-e4e067a0c575.png)

### Please make all the required changes before you request another code review.
## Happy Coding :tophat:

2020-07-01 00:17 UTC, rammazzoti2000 requested changes
### Hello @SajjadAhmad14 :wave: I am Alex your code reviewer for this project
You did great job on this project, good use of bootstrap, readme file descriptive although is showing only when I click on it and not the root directory of the repo.

### :stop_sign: Required Changes :construction: :construction_worker: 
- [ ] HTML code doesn't pass validation please use [this validator ](https://validator.w3.org/#validate_by_input) by direct input for more information
![image](https://user-images.githubusercontent.com/3244654/86187232-9a098080-bb3b-11ea-89d4-c795eb8f8fa6.png)
- [ ] Your sections are not using labels in the bottom left as the original page, some are showing but only text without a background while some are totally missing, please compare your page with the original one for better comparison
### Orignal
![image](https://user-images.githubusercontent.com/3244654/86188352-a8a56700-bb3e-11ea-9753-28b330c0b67f.png)
### Clone
![image](https://user-images.githubusercontent.com/3244654/86188297-827fc700-bb3e-11ea-9ddd-6ba73a240ffb.png)


### Large Screens
- [ ] The `Subscribe` & `Newsletter` sections are missing some contrast like background color and also some border on `Newsletter` section. As for the footer the logo is way too big and the social icons are not the same color, and same goes for the elements inside `Subscribe` & `Newsletter`, please compare your page against the original one for better comparison.
### Original
![image](https://user-images.githubusercontent.com/3244654/86187877-341df880-bb3d-11ea-88a5-f16b6ae279ba.png)
### Clone
![image](https://user-images.githubusercontent.com/3244654/86187861-26687300-bb3d-11ea-8d83-035d48d18cfe.png)
- [ ] You can notice when resizing the page around 1008px the navbar logo gets smaller for no reason
![image](https://user-images.githubusercontent.com/3244654/86188040-b5758b00-bb3d-11ea-81b3-5850183f936d.png)

### Medium Screens
- [ ] You can notice this advertisement elements along with `signup` card should be center and the elements inside `signup` card are too big check you page against the original one for better comparison
### Original
![image](https://user-images.githubusercontent.com/3244654/86188209-3a60a480-bb3e-11ea-8b06-58200a26b483.png)
### Clone
![image](https://user-images.githubusercontent.com/3244654/86188199-2fa60f80-bb3e-11ea-8c64-91aa06fe7f8d.png)
- [ ] The `Subscribe` section is not the same as the original, check out bellow :point_down: 
### Original
![image](https://user-images.githubusercontent.com/3244654/86188543-400aba00-bb3f-11ea-957d-537538d9cfd4.png)
### Clone
![image](https://user-images.githubusercontent.com/3244654/86188528-31240780-bb3f-11ea-821d-adf752fff761.png)

### Small Screens
- [ ] The navbar logo is quite big
![image](https://user-images.githubusercontent.com/3244654/86189144-033fc280-bb41-11ea-8d25-66ff1fc6cd05.png)
- [ ] The `My Turn` & `Culture and Travel` sections are not stretching on the entire width of the screen
### Original
![image](https://user-images.githubusercontent.com/3244654/86188710-ca531e00-bb3f-11ea-9f4a-09390b697cd4.png)
### Clone
![image](https://user-images.githubusercontent.com/3244654/86188692-be675c00-bb3f-11ea-998f-73151986bd4e.png)
- [ ] The articles from each specific section (Business, US, World etc.) have this huge gap between the thumbnail and title description
![image](https://user-images.githubusercontent.com/3244654/86188808-17cf8b00-bb40-11ea-8d02-14ee7f3ff0ed.png)
- [ ] `Subscribe` and `Newsletter` need some work, please compare your page against the original one
### Original
![image](https://user-images.githubusercontent.com/3244654/86189029-ad6b1a80-bb40-11ea-86b6-9235d88c8d47.png)
![image](https://user-images.githubusercontent.com/3244654/86189043-b8be4600-bb40-11ea-8ce8-e87dcfdbfe9d.png)

### Clone
![image](https://user-images.githubusercontent.com/3244654/86189062-c5429e80-bb40-11ea-86fb-0ce7814522f6.png)
![image](https://user-images.githubusercontent.com/3244654/86189082-cffd3380-bb40-11ea-95c1-c4d47e781f74.png)

- [ ] The footer also needs some adjustments
![image](https://user-images.githubusercontent.com/3244654/86189119-ed320200-bb40-11ea-896e-9de032ec4181.png)

### <em>Kindly fix the REQUIRED issues and send another code review request.

Cheers and Happy coding! :clap: 

Code review by Alexandru Bangau

(Feel free to contact me on slack by the handle of **_alexandru_** if you have any additional question)</em>
### :stop_sign: Status: Required Changes

2020-07-04 01:05 UTC, voscarmv requested changes
# Nice work so far. 👍 
## However, there are some changes required 👀 🧰 🔨 🔧 

- The original page has spacing on the sides. Your version is missing the gray space on the sides of the page. Please add this spacing to your version.

| Your version | Original page |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/86502278-0b794700-bd67-11ea-88cb-bded73c985c8.png) | ![image](https://user-images.githubusercontent.com/2739245/86502264-f3092c80-bd66-11ea-97f4-d928aea8913f.png) |

- Your version is missing the LOGIN link on the Medium Display.

| Your Version | Original page |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/86502308-6448df80-bd67-11ea-990d-f8bfa23187b7.png) | ![image](https://user-images.githubusercontent.com/2739245/86502314-71fe6500-bd67-11ea-811f-7c7f838497dd.png) |

- The side thumbnails from the bottom articles appear stretched. Please fix this.

![image](https://user-images.githubusercontent.com/2739245/86502419-7a0ad480-bd68-11ea-9a12-f7bb34a98d2d.png)

- The Subscribe and Newsletter sections have different heights at some points while resizing the page. Please make sure that they have the same height where it corresponds. Also, the phone image from the Newsletter section appears stretched. Make sure the aspect ratio is preserved while resizing.

| Your version | Original page |
| --- | --- |
| ![image](https://user-images.githubusercontent.com/2739245/86502380-1c768800-bd68-11ea-9d16-9d54961966b0.png) | ![image](https://user-images.githubusercontent.com/2739245/86502384-25fff000-bd68-11ea-8adf-d4326d98f6f1.png) |

### Submit these changes and request a new code review! 😄 👍 
### Questions or comments? Reach me on [Twitter](https://twitter.com/voscarmv) or [LinkedIn](https://linkedin.com/in/oscar-mier) 🧑‍💻🗨️🧑‍💻 
# Happy Hacking! 🧠 ⌨️ 🖱️ 🖥️

2020-07-04 08:33 UTC, tirthajyoti-ghosh requested changes
# Status: Changes required 🛑

## Hello @SajjadAhmad14 👋. You have done a great job making this project 💯 ! 

### However, we still need to work on some changes.

- Your README file has a typo(`RAEDME`) in its filename. That's why it's not showing in your repo.
![image](https://user-images.githubusercontent.com/57726348/86508398-534aad80-bdfd-11ea-8810-1a79d7cd21ee.png)

- Increase the margin on both sides of your clone.

- Please fix the navbar.

#### Clone
![image](https://user-images.githubusercontent.com/57726348/86508434-b5a3ae00-bdfd-11ea-8e81-3240fb7afaf9.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86508455-c6ecba80-bdfd-11ea-93dc-48ab2396afd0.png)

- Decrease the size of the images in this section 👇
![image](https://user-images.githubusercontent.com/57726348/86508475-e7b51000-bdfd-11ea-8b46-151cc4584469.png)

#### Original
![image](https://user-images.githubusercontent.com/57726348/86508482-f69bc280-bdfd-11ea-8dc1-9da3f039677c.png)

- Please make this look like original 👇

#### Clone

> Desktop

![image](https://user-images.githubusercontent.com/57726348/86508517-4b3f3d80-bdfe-11ea-8511-dfb1a61bf6bc.png)

>Mobile

![image](https://user-images.githubusercontent.com/57726348/86508558-8f324280-bdfe-11ea-96f9-0c9f54e7cb98.png)


#### Original

> Desktop

![image](https://user-images.githubusercontent.com/57726348/86508528-5befb380-bdfe-11ea-9922-2e7d496f74ff.png)

> Mobile

![image](https://user-images.githubusercontent.com/57726348/86508568-9ce7c800-bdfe-11ea-9f1b-279acf05fa8e.png)


Apply these changes and request another review.


Happy coding 👨‍💻

2020-07-06 23:30 UTC, andresporras3423 requested changes
### Status: Changes Required :recycle:
**Hello @SajjadAhmad14** 
Good job with your new submission for this project :muscle:  
Your page really looks like the original :clap: :clap: :clap:  
Your page passes most of the requirements. There are just a few details to improve before you can go ahead:
- [ ] Don't overuse ID Selectors
- [ ] Don't repeat yourself, in order to minimize code you can group selectors with the same style definition, or you can create a new class.

Please request another review once you are ready! :+1: 

Happy coding :relaxed:

Oscar Andrés Russi Porras

2020-07-06 23:30 UTC, andresporras3423 commented on assets/css/style.css
> +}
Group selectors:
`
.container-fluid, .container {
  font-family: "Roboto Condensed", sans-serif;
}
`
Or create a new class:
`
.<new_class_name> {
  font-family: "Roboto Condensed", sans-serif;
}
`

2020-07-06 23:30 UTC, andresporras3423 commented on assets/css/style.css
> +}
Group selectors, or create a new class

2020-07-06 23:30 UTC, andresporras3423 commented on assets/css/style.css
> +  text-decoration: none;
Group selectors or create a new class.

2020-07-06 23:30 UTC, andresporras3423 commented on assets/css/style.css
> +}
group selectors, or create a new class

2020-07-06 23:30 UTC, andresporras3423 commented on assets/css/style.css
> +}
Group selectors, or create a new class. Don't overuse ID selectors.

2020-07-07 01:16 UTC, elmejdki approved these changes
# status: approved :heavy_check_mark: 
## Great job guys your clone looks really good :clap: :100: :1st_place_medal:  , thank you for making the required changes.

- now you can merge to master your project is approved.

## Happy Coding :tophat:

2020-07-07 14:46 UTC, merged